name: labs
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^4.2.1
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  ml_linalg: ^13.10.0
  extended_math: ^0.0.9
  event_bus: ^2.0.0
  sprint: ^1.0.4
  binary: ^3.0.1
  fl_chart: ^0.55.2
  threading: ^0.0.10
  easy_isolate: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^4.2.0
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  flutter_staggered_grid_view: ^0.6.2
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1


flutter:
  uses-material-design: true
